global:
  scrape_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - localhost:9093


rule_files:
  - "/etc/prometheus/rules.yaml"


scrape_configs:
  - job_name: "prometheus"
    scheme: "https"
    static_configs:
      - targets: ["example.com"]
    basic_auth:
      username: "username"
      password_file: "/etc/prometheus/password"

  - job_name: "example2.com"
    scheme: "https"
    static_configs:
      - targets: ["example2.com"]
    basic_auth:
      username: "username"
      password_file: "/etc/prometheus/password"

  - job_name: "app"
    scheme: "http"
    static_configs:
      - targets: ["localhost"]


